# Generated by Django 2.2.4 on 2019-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_continents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continents',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
