# Generated by Django 2.2.4 on 2019-08-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20190830_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('names', models.CharField(max_length=50)),
                ('codephone', models.CharField(max_length=50)),
                ('codetelf', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('names', models.CharField(max_length=50)),
                ('codephone', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lenguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('names', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='peoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('firstnames', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('surenames', models.CharField(max_length=50)),
                ('birthdate', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
