# Generated by Django 2.2.4 on 2019-09-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_cities_countries_lenguages_peoples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='cities',
        ),
        migrations.DeleteModel(
            name='continents',
        ),
        migrations.DeleteModel(
            name='countries',
        ),
        migrations.DeleteModel(
            name='foto',
        ),
        migrations.DeleteModel(
            name='lenguages',
        ),
        migrations.DeleteModel(
            name='peoples',
        ),
    ]
